# Ensure journald is configured to send logs to rsyslog -> ForwardToSyslog=yes
# Ensure journald is configured to compress large log files -> Compress=yes
# Ensure journald is configured to write logfiles to persistent disk -> Storage=persistent

---
- name:  Ensure journald is configured to send logs to rsyslog
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.string }}"
    line: "{{ item.line }}"
  with_items: 
    - {string: ^#ForwardToSyslog, line: ForwardToSyslog=yes}
    - {string: ^#Compress, line: Compress=yes}
    - {string: ^#Storage, line: Storage=persistant}